### ISSUE TITLE
Minor request of changing the way "status" text is displayed in Unclosed Request Review Script 

### ISSUE THREAD

**Issue by kayesshu** [SO-Close-Vote-Reviewers/UserScripts#116]
At certain "high" resolutions (> 1680x1050) the "status" text of a cv-pls is kinda confusing to _me_. 

For instance, could we change "cld" to "Cld"? Because many times I need to closely focus my eyes on the display to see whether is "cld" or "dld".

Screenshot attached with the necessary red free-hand drawn circle to illustrate this ["issue"](https://i.imgur.com/k2Omwix.png).

**Comment by makyen** [comment]
Let me see how that looks. I vaguely recall previously trying it with `Cld` and not liking how it looked/fit with the other marking (e.g. all the other labels have no caps, which fits with SE's strong tendency not to use capital letters).

However, my evaluation is colored by knowing in advance that "dld" is not possible due to the SE API returning no information for deleted posts. Thus, if it makes it clearer, that would be better.

**Comment by makyen** [comment]
I didn't really like how `Cld` looked. So, I tried adding a pixel between the `c` and the `l` to try to make the characters a bit more distinct.
Here is what that looks like:



##### In Chrome as it was when reported:
[![enter image description here][1]][1]
[![enter image description here][2]][2]
Full size:  
[![enter image description here][3]][3]

##### With proposed change:
[![enter image description here][4]][4]
[![enter image description here][5]][5]
Full size:  
[![enter image description here][6]][6]

For me, the above change makes it significantly more readable. Does the above solve the problem for you?

  [1]: https://i.stack.imgur.com/SzFAy.png
  [2]: https://i.stack.imgur.com/dEt63.png
  [3]: https://i.stack.imgur.com/impRU.png
  [4]: https://i.stack.imgur.com/ckUxv.png
  [5]: https://i.stack.imgur.com/85w4h.png
  [6]: https://i.stack.imgur.com/DZ2kk.png

**Comment by kayesshu** [comment]
Yep, pretty much! Thanks for your work!
