### ISSUE TITLE
Allow a user to choose if links to user profiles to the left of chat messages turn blue

### ISSUE THREAD

**Issue by gunr2171** [SO-Close-Vote-Reviewers/UserScripts#118]
As a standard chat user, I'm used to seeing only moderators' names in blue. Suddenly, people's names become blue and I get confused for a second.

![image](https://user-images.githubusercontent.com/8290105/36612089-8fed281e-18a3-11e8-89de-2167d7038bce.png)

Yes, yes, I know (after the split second that my brain recalls the information) that those users are not moderators but just links to chat profiles that I have visited. True moderators also have a diamond prepended to their name.

But still, I'd rather not be surprised when I switch back to the chat room.

I'd like the "Blue visited links and show ♦ for moderators." option to be split out into multiple options.

![image](https://user-images.githubusercontent.com/8290105/36612534-e224adcc-18a4-11e8-9299-f2e98cc906aa.png)

Bonus points:
The "turn blue on visit" applies to _EVERY_ link on the page. You might want to break down the options more, like

- The starboard area
- Room links (the `sidebar-menu` id)
- The "all rooms" button at the top

**Comment by Tyler-H** [comment]
I would recommend just adding an overriding style to the user profile links on the lefthand side. There's no need to make them blue, especially when blue normally means 'moderator'.

**Comment by makyen** [comment]
Some details:
1) I'm good with having a separate option to enable the user profile links to the left of chat messages being blue for visited. (default: not blue) I'd prefer it as an option, as I find the information useful. It helps indicate to me that a user is new to SOCVR, due to their name not being blue.

2) Should there be an option to completely not affect the sidebar?

3) In the sidebar what should be indicated with blue visited? Particularly, should user profile links follow the selection for (1) above?

Image for identification:  
[![top half of sidebar][1]][1]



With respect to the above image:
* **Buttons:** Clearly buttons. Shouldn't turn blue; no option to do so.
* **Links:** These are links, despite "info" being grouped with other buttons. IMO: it makes sense to have these turn blue.
* **User Links** (sidebar only) While this is a link to the user's chat-profile, it normally gives no indication of the moderator status of the user (i.e. it's not blue for moderators, and doesn't have the class indicating a moderator, or RO). Should there be a separate option to not turn these blue? If so, should they be blue when visited by default?

  [1]: https://i.stack.imgur.com/AHg5z.png

**Comment by gunr2171** [comment]
I am satisfied with the changes implemented in 1.1.1.0. 👍
