### ISSUE TITLE
No request gets sent from mobile Firefox

### ISSUE THREAD

**Issue by honnza** [SO-Close-Vote-Reviewers/UserScripts#137]
When I cast a closevote and check "send cv-pls request", the vote is cast successfully, but no request is made, and no error message appears either - a silent failure.

When I try to send a standalone request, clicking the Send button has no effect and the dialog stays open. The request reason input is still editable, and the dialog still closes when a click outside the dialog is made. The room selector works just fine.

Script version: 1.6.1
Tampermonkey version: 4.7.5788
Firefox version: 61.0
Android version: 7.1.1
Android kernel version: 3.1.49-12476963
Hardware: Samsung J5, SM-J510FN

**Comment by makyen** [comment]
We're going to need some effort to duplicate the problem. If anyone else wants to try to duplicate it, that would be helpful.

There's a bit of context in chat. First in [SOCVR](https://chat.stackoverflow.com/transcript/message/43285580#43285580), then in the [SOCVR Testing Facility](https://chat.stackoverflow.com/transcript/message/43285864#43285864)

I was unable to duplicate the problem. In other words, I was able to send requests using the popup dialog without problem (see testing facility) from Firefox 61.0 (and earlier) using Greasemonkey, Tampermonkey, and Violentmonkey.

**Comment by makyen** [comment]
Thanks for the report.

I'm closing this issue due to:
* The age of the problem report and that there have been many browser updates since this time that affect userscript manager operation, even completely disabling it, particularly on mobile Firefox.
* There's been a major update in the userscript since this time, which changed the code in this area significantly.

If this still an issue, please post a new comment here, reopen this issue, or create a new issue. Thanks.
