### ISSUE TITLE
CV request generator: No cv-pls checkbox in Close question dialog after editing the question

### ISSUE THREAD

**Issue by vkotovv** [SO-Close-Vote-Reviewers/UserScripts#139]
Steps to reproduce:
- Edit the question (and hit Save to apply edits)
- Click Close
- There is no "Send cv-pls request" checkbox in Close question dialog

If you hit Refresh button in browser on this page, dialog will now work again correctly.

Version 1.6.1

**Comment by makyen** [comment]
This should be resolved in the current [alpha version of the Request Generator](https://chat.stackoverflow.com/transcript/message/44505590#44505590). Please verify that the alpha version resolves this.

**Comment by vkotovv** [comment]
@makyen This is still not fixed in 1.6.11, I just reproduced it. See steps in the description.

**Comment by makyen** [comment]
There's no expectation that this will be fixed in 1.6. It should be fixed in all 1.8 versions (the alpha version) ([GitHub](//git.io/SOCVR-CVRG-MakNewVer)) ([install](//github.com/SO-Close-Vote-Reviewers/UserScripts/raw/CVRG-Mak-new-version/SECloseVoteRequestGenerator.user.js)). Being able to resolve this was one of the reasons for the substantial changes from the current release version to the current alpha version.

How the Request Generator handles detection of where and when to place the `cv-pls` button and how the script detects the close-vote and close-flag popups were all rewritten in order to enable fixing this issue, some other issues, and permit new functionality.

**Comment by makyen** [comment]
Thanks for the report. It looks like this was resolved by switching the repository over to the 2.X version of the Request Generator. If it's still an issue, please post a new comment here, reopen this issue, or create a new issue.
